version: '3.9'

services:
  front:
    container_name: 'front'
    build:
      context: front/
      dockerfile: Dockerfile
    environment:
      PORT: 3001
    ports:
      - 3001:3001
    networks:
      - internal
  server:
    container_name: 'server'
    build:
      context: server/
      dockerfile: Dockerfile
    environment:
      NODE_PORT: 3000
      MONGO_USERNAME: 'admin'
      MONGO_PASSWORD: 'admin'
      MONGO_DATABASE: 'test-db'
      MONGO_HOST: 'mongo'
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - internal
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - ./dev/db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
      MONGO_INITDB_DATABASE: 'test-db'
    ports:
      - 27017:27017
    networks:
      - internal
networks:
  internal:
    driver: bridge
